name: Republish

on:
  schedule:
    - cron: '15 10 * * *'  # Run at 10:15 pm UTC every day.

# For debugging only
# on: push

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $USER_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/saltomentale/blog/pages/builds
          
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}